name: /home/jovyan/EnergyForecastChallenge/env
channels:
  - conda-forge
dependencies:
  - python==3.9
  - papermill
  - nbconvert
variables:
  R_LIBS_USER: ''
  - pip:
    - black==22.10.0
    - brotlipy==0.7.0
    - colorama==0.4.6
    - importlib-resources==5.10.1
    - nbconvert==7.2.7
    - papermill==2.3.4
    - pip-chill==1.0.1
    - pkgutil-resolve-name==1.3.10
    - pyopenssl==22.1.0
    - pysocks==1.7.1
